server:
  port: 8090
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"   # set default profile which needs to be activated

# expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"