build:
  version: 2.0

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Rahul - QA Lead"
    email: "rahul@gmail.com"
  onCallSupport:
    - (555) 555-1346
    - (555) 456-3245