build:
  version: 3.0

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Harsh Gandhi - Developer"
    email: "harshgandhi043@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345