server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"    # we use optional tag to run accounts microservice even if it is unable to connect config server
  profiles:
    active: "default"   # set default profile which needs to be activated

# Use this to run rabbitmq container:  docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.13-management

# expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
