server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Harsh Gandhi - Developer"
    email: "harshgandhi043@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345